import{s as I,i as _,g as R,a as C,b as z,c as T,d as N,e as O}from"./assets/mob-menu-d0c98757.js";import{i as L}from"./assets/vendor-372b0e6c.js";import"https://cdn.jsdelivr.net/npm/axios@1.3.5/+esm";const U="add to shopping list",W="remove from the shopping list",S=document.querySelector("body"),i=document.querySelector("#modalBookContainer"),j=i.querySelector("#modalClose"),m=i.querySelector("#shoppingListBtn"),v=i.querySelector("#bookCover"),P=i.querySelector("#bookTitle"),Q=i.querySelector("#bookAuthor"),V=i.querySelector("#bookDescription"),Y=i.querySelector("#amazonLink"),F=i.querySelector("#iBookLink");j.addEventListener("click",k);m.addEventListener("click",J);modalBookBackground.addEventListener("click",X);let d,E,a;document.addEventListener("keyup",t=>{t.code==="Escape"&&k()});async function G(t){a=t,E=await R(a),d=_(a),K(E,d),i.classList.remove("visually-hidden"),i.classList.add("modal-book-container-show"),S.classList.add("overflow-hidden")}function k(){i.classList.add("visually-hidden"),i.classList.remove("modal-book-container-show"),S.classList.remove("overflow-hidden")}function J(){I(a),d=_(a),q(d)}function K(t,e){var h,f;const{book_image:o,author:n,title:l,description:$,buy_links:y}=t,H=((h=y.find(u=>u.name==="Amazon"))==null?void 0:h.url)||"https://www.amazon.com/",D=((f=y.find(u=>u.name==="Apple Books"))==null?void 0:f.url)||"https://www.apple.com/apple-books/";v.setAttribute("src",o),v.setAttribute("alt",l),P.textContent=l,Q.textContent=n,V.textContent=$,Y.setAttribute("href",H),F.setAttribute("href",D),q(e)}function q(t){t?(m.textContent=W,bookCongratulations.classList.remove("visually-hidden")):(m.textContent=U,bookCongratulations.classList.add("visually-hidden"))}function X(t){t.target===t.currentTarget&&k()}function Z(){L.show({message:"There are no more books in this category",position:"topRight",backgroundColor:"#eac645"})}function tt(){L.show({message:"There are no more categories in this library",position:"topRight",backgroundColor:"#eac645"})}const s={topListElem:document.querySelector("#topList"),categoryListElem:document.querySelector("#categoryList"),titleElement:document.querySelector(".top_list-title"),allCategoriesElement:document.querySelector(".all-categories")};let p=!1;document.addEventListener("DOMContentLoaded",function(){document.addEventListener("click",nt),document.addEventListener("click",c),document.addEventListener("click",st),window.addEventListener("scroll",it)});document.addEventListener("DOMContentLoaded",async function(){C(s.titleElement),s.topListElem.innerHTML="";const e=await z();let o="";e.forEach(n=>{o+=et(n)}),s.topListElem.innerHTML=o,T()});function et(t){return`
        <li class="top_list-container">
            <h2 class="top_list-category_name">${t.list_name}</h2>
            <ul class="top_list-cards">${ot(t.books)}</ul>
            <button class="top_list-see_more" data-category="${t.list_name}">See More</button>
        </li>
    `}function ot(t){let e=1;const o=t.map(n=>`
        <li class="top_list-card" data-book-sequence-number="${e++}">
            <div class="top_list-book_cover_wrapper" data-bookid="${n._id}" tabindex="0">
                <img class="top_list-book_cover" src="${n.book_image}" alt="${n.title}">
                <div class="quick-view-text">Quick view</div>
            </div>
            <h3 class="top_list-book_title">${n.title}</h3>
            <p class="top_list-book_author">${n.author}</p>
        </li>
    `).join("");return e++,o}const c=function(t){var e;if((e=t.target.parentElement)!=null&&e.classList.contains("top_list-book_cover_wrapper")){const o=t.target.parentElement.dataset.bookid;G(o)}},nt=function(t){if(t.target.classList.contains("top_list-see_more")){s.topListElem.classList.add("hidden"),s.categoryListElem.classList.remove("hidden");const e=t.target.dataset.category;B(e),b(e),document.removeEventListener("click",c),document.addEventListener("click",c),r(),g(e)}if(t.target.classList.contains("gallery-link")){s.topListElem.classList.add("hidden"),s.categoryListElem.classList.remove("hidden");const e=t.target.textContent.trim();B(e),b(e),r(),document.removeEventListener("click",c),document.addEventListener("click",c),r(),g(e)}},st=async function(t){t.target.classList.contains("all_categories")&&(s.titleElement.innerHTML="Best Sellers <span>Books</span>",s.categoryListElem.classList.add("hidden"),s.topListElem.classList.remove("hidden"),r(),g("All categories")),t.target.classList.contains("link")&&(s.titleElement.innerHTML="Best Sellers <span>Books</span>",s.categoryListElem.classList.add("hidden"),s.topListElem.classList.remove("hidden"),r())};async function b(t){C(s.titleElement),s.categoryListElem.innerHTML="";const o=await N(t);let n="";o.forEach(l=>{n+=`
        <li class="category_list-card">
            <div class="top_list-book_cover_wrapper" data-bookid="${l._id}" tabindex="0">
                <img class="top_list-book_cover" src="${l.book_image}" alt="${l.title}">
                <div class="quick-view-text">Quick view</div>
            </div>
            <h3 class="top_list-book_title">${l.title}</h3>
            <p class="top_list-book_author">${l.author}</p>
        </li>
        `}),n+='<li><button class="all_categories">All Categories</button></li>',s.categoryListElem.innerHTML=n,T()}function B(t){const o=t.split(" "),n=o.pop();s.titleElement.textContent=o.join(" ");const l=document.createElement("span");l.textContent=" "+n,s.titleElement.appendChild(l),p=!1}function it(){const t=document.querySelector(".all_categories");if(t){const e=t.getBoundingClientRect(),o=window.innerHeight||document.documentElement.clientHeight;e.top<o&&!p&&s.topListElem.classList.contains("hidden")&&(Z(),p=!0)}}function r(){const t=window.innerWidth||document.documentElement.clientWidth,e=s.titleElement;t<1440&&setTimeout(function(){const o=e.getBoundingClientRect().top-60;window.scrollTo({top:o,behavior:"smooth"})},1100)}let w;function lt(){return window.innerHeight+window.scrollY>=document.body.offsetHeight}window.addEventListener("scroll",function(){lt()&&(clearTimeout(w),w=setTimeout(function(){s.titleElement.textContent.trim()==="Best Sellers Books"&&tt()},500))});function g(t){const e=document.querySelector(".link"),o=document.querySelector(".sidebar");s.allCategoriesElement.querySelectorAll(".gallery-link").forEach(n=>{t===n.textContent.trim()?(n.classList.add("active"),e.classList.remove("all-categories-link"),o.scrollTop=n.offsetTop-o.offsetTop):n.classList.remove("active")})}const ct=document.querySelector(".all-categories");function at(t){return t.map(o=>`
            <li class="gallery-item">
            <a class="gallery-link" href=#>${o.list_name}
            </a>
          </li>`).join("")}function rt(t){ct.insertAdjacentHTML("beforeend",t)}O().then(t=>at(t)).then(t=>{rt(t),dt(),ut()}).catch(t=>L.error({maxWidth:"432px",messageColor:"rgb(250, 250, 251)",messageSize:"16px",backgroundColor:"rgb(239, 64, 64)",position:"topRight",message:`${t}`}));function dt(){const t=document.querySelectorAll(".gallery-link"),e=document.querySelector(".link");t.forEach(o=>{o.addEventListener("click",()=>{e.classList.remove("all-categories-link")})})}function ut(){const t=document.querySelectorAll(".gallery-link");let e=0;t.forEach((o,n)=>{o.addEventListener("click",()=>{t[e].classList.remove("active"),e=n,t[e].classList.add("active")})})}const x=document.getElementById("scrollToTopBtn");document.body.scrollTop=0;document.documentElement.scrollTop=0;x.addEventListener("click",pt);window.addEventListener("scroll",mt);function mt(){document.body.scrollTop>20||document.documentElement.scrollTop>20?(document.getElementById("scrollToTopBtn").style.display="block",x.classList.remove("visually-hidden")):document.getElementById("scrollToTopBtn").style.display="none"}function pt(){window.scrollTo({top:0,behavior:"smooth"})}const A=document.getElementsByTagName("html")[0],gt=document.querySelector(".header-btn"),Lt=document.querySelector(".form-signup-close"),M=document.querySelector(".sign-up");gt.addEventListener("click",()=>{A.classList.add("no-scroll-signup"),M.classList.add("signup-is-active")});Lt.addEventListener("click",()=>{A.classList.remove("no-scroll-signup"),M.classList.remove("signup-is-active")});
//# sourceMappingURL=commonHelpers.js.map
